# Generated by Django 3.2.8 on 2022-01-25 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0003_alter_userprofile_name'),
        ('reddit', '0003_subreddit'),
    ]

    operations = [
    ]
