# Generated by Django 3.2.8 on 2022-01-25 20:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0004_merge_0003_alter_userprofile_name_0003_subreddit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreddit',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='administered_subreddits', to=settings.AUTH_USER_MODEL),
        ),
    ]
