# Generated by Django 3.2.8 on 2022-01-25 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0005_alter_subreddit_admins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreddit',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_subreddits', to=settings.AUTH_USER_MODEL),
        ),
    ]
